apiVersion: v1
kind: Service
metadata:
  name: systemize-user-api-alb
  labels:
    app: systemize-user-api
spec:
  selector:
    app: systemize-user-api
  ports:
  - port: 80
    protocol: TCP
    targetPort: 3000