apiVersion: apps/v1
kind: Deployment
metadata:
  name: systemize-user-api
spec:
  selector:
    matchLabels:
      app: systemize-user-api
  replicas: 2
  template:
    metadata:
      labels:
        app: systemize-user-api
    spec:
      containers:
      - name: systemize-user-api
        image: systemize-user-api:latest
        ports:
          - containerPort: 3000
        livenessProbe:
          initialDelaySeconds: 20
          periodSeconds: 5
          httpGet:
            path: /health
            port: 3000